# Generated by Django 4.0.6 on 2022-09-07 16:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('number', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('number', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('beds', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)])),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='visitors.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('active', models.BooleanField()),
                ('rooms', models.ManyToManyField(related_name='reservations', to='visitors.room')),
                ('visitors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.visitor')),
            ],
        ),
    ]
